const friends = [
    {
      "name": "Muhammad Dennisa",
      "location": "KualaLumpur",
      "school_sd": "SD 1",
      "school_smp": "SMP 2",
      "school_sma": "SMA 1 Medan",
      "job": "Solution Architect, Product Manager",
      "link_wa": "https://wa.me/+6285761807229",
      "link_fb": "https://www.facebook.com/mdennisa",
      "link_ig": "https://www.instagram.com/mdennisa/",
      "link_twitter": "",
      "link_linkedin": "https://www.linkedin.com/in/mdennisa/",
      "img": "./images/profiles/mdennisa.jpg",
      "summary": "Menyediakan jasa konsultasi IT, digital startup, web development, UX dan design"
    },
    {
      "name": "Muhammad Fifin Kombih",
      "location": "Surabaya",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "",
      "job": "Dokter",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "EMILIA GUSTIKA HADI",
      "location": "Jakarta",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "",
      "job": "Dentist",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Reny amalia anastasya ",
      "location": "Pekanbaru ",
      "school_sd": "",
      "school_smp": "SMP 2",
      "school_sma": "",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Muhammad ichsan",
      "location": "Bireuen",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "",
      "job": "Kementerian agama ",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Immanuel Christian Sinaga",
      "location": "Medan",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "",
      "job": "Freelance",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Lena Romawana",
      "location": "BandaAceh",
      "school_sd": "",
      "school_smp": "",
      "school_sma": "",
      "job": "PT HM SAMPOERNA TBK",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Muhammad al fatah",
      "location": "Medan",
      "school_sd": "",
      "school_smp": "SMP 2",
      "school_sma": "",
      "job": "Wirausaha",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Danu Hermanu",
      "location": "CikarangBarat",
      "school_sd": "SD 4",
      "school_smp": "SMP 1",
      "school_sma": "SMK PANCA BUDI, Medan",
      "job": "PT. HM. Sampoerna. Tbk",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Cut Rozy Rizkiany",
      "location": "KualaSimpang",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Bidan",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Ruranha",
      "location": "Tangerang",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMU PLUS AL-AZHAR MEDAN",
      "job": "Senior Consultant Offshore and Maritime",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Yusran Bani",
      "location": "Lhokseumawe",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Staff IT UPT TIK Universitas Malikussaleh",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Reza Mahnur",
      "location": "Lhokseumawe",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "PNS",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "ratna ningsih",
      "location": "Meulaboh",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "jualan motor",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Lona Gultom",
      "location": "JakartaTimur",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "Advokat, Jasa Hukum",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Nasrullah (Tino)",
      "location": "JakartaTimur",
      "school_sd": "SD 4",
      "school_smp": "SMP 1",
      "school_sma": "SMUN 1 Medan",
      "job": "PT. Jasa Marga (Persero) Tbk.",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Arismunandar",
      "location": "TangerangSelatan",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA Krida Nusantara, bandung",
      "job": "Profesional ",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Ulli Agusti",
      "location": "Lhokseumawe",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Muhammad Ivan Fikriadi",
      "location": "Bandung",
      "school_sd": "SD 4",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Pegawai Swasta di PT. Hariff Daya Tunggal Engineering bidang Rectifier & Baterai Telekomunikasi.",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": "Usaha sampingan jadi coach diet online"
    },
    {
      "name": "Muhammad Afrizal",
      "location": "Bandung ",
      "school_sd": "SD 4",
      "school_smp": "SMP 2",
      "school_sma": "Kartika 1-2 medan",
      "job": "ASN",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Rully",
      "location": "BandaAceh",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "PNS",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Yessy Arina",
      "location": "Medan",
      "school_sd": "SD 2",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "PNS KLHK",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Arieci Maulana",
      "location": "JakartaTimur",
      "school_sd": "SD 2",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Tri Setyadi",
      "location": "SulawesiTengah",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "Yogyakarta",
      "job": "Environtmental Consulting",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Robby Ilham",
      "location": "Makassar",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMU ADABIAH Padang",
      "job": "Airnav Indonesia",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Muhammad Rizki Rinaldi",
      "location": "TangerangSelatan",
      "school_sd": "SD 2",
      "school_smp": "SMP 1",
      "school_sma": "SMA Medan",
      "job": "Konstruksi",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Reny amalia ",
      "location": "Pekanbaru ",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Siska Ananda (Ciko) ",
      "location": "BlangPidie",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "Dokter",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "MIRZA MOSADDEQ SHAH",
      "location": "TanjungPinang",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "PERUMDA AIR MINUM TIRTA KEPRI sebagai HRD",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Hendra Noval",
      "location": "Bireuen",
      "school_sd": "SD 1",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "POLRI",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Astrid Adelinna",
      "location": "Cirebon",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMU Negeri 1 Cirebon",
      "job": "Mompreneur HDI",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Dina Tiffany",
      "location": "Medan",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Wirausaha",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Fadlan Syafriza",
      "location": "Yogyakarta",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Criya Keumalasari",
      "location": "Jakarta",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "Bandung",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Fadli Hariadi ",
      "location": "Bandung ",
      "school_sd": "SD 2",
      "school_smp": "SMPN 3 Banda Aceh ",
      "school_sma": "SMA YAPENA",
      "job": "Dosen PTS",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Fadjaruddin Nur",
      "location": "Bandung",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "www.tamitaartha.co.id",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Nita pahlevi",
      "location": "KENDAL",
      "school_sd": "PT pupuk iskandar muda",
      "school_smp": "PT Pupuk iskandsr muda",
      "school_sma": "SMA YAPENA",
      "job": "Ibu rumah tangga",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Ian Fahmi",
      "location": "BandaAceh",
      "school_sd": "SD 1",
      "school_smp": "Medan",
      "school_sma": "SMA YAPENA",
      "job": "Perbankan Syariah",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Johan triputra",
      "location": "Bekasi",
      "school_sd": "SD 4",
      "school_smp": "SMP 1",
      "school_sma": "Smun 12 medan",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "LENA ROMAWANA",
      "location": "BANDAACEH",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "KELAS 1 DI SMA YAPENA, KELAS 2-3 PINDAH KE JOGJA",
      "job": "PT HM SAMPOERNA TBK",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Dira Yuwana Putri",
      "location": "Bireuen",
      "school_sd": "SD 3",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Muhammad Reza ",
      "location": "Kuningan",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "Dokter spesialis urologi ",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Husna Indriyani",
      "location": "Bandung",
      "school_sd": "SD 1",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Rafiqoh Purnamasari",
      "location": "Medan",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Rumah Blepots",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "IRSYAD RAZAQI",
      "location": "BONTANG",
      "school_sd": "SD 4",
      "school_smp": "SMP 1",
      "school_sma": "Udah Pindah ke SMA46 Jakarta",
      "job": "Karyawan Swasta - Tukang Insinyur",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "M. Yasin Arifin",
      "location": "LubukPakam",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMU Negeri 4 Tebing Tinggi",
      "job": "Polri",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Najmul Ikhwan",
      "location": "Bandung",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "Grab Driver ",
      "link_wa": "https://wa.me/+628562220373",
      "link_fb": "",
      "link_ig": "https://www.instagram.com/ikhwan_najmul/",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "./images/profiles/najmul.jpg",
      "summary": ""
    },
    {
      "name": "Amalia Husein ",
      "location": "Singapore",
      "school_sd": "SD 4",
      "school_smp": "SMP 1",
      "school_sma": "Tangerang",
      "job": "Project Engineer di JGC Singapore, oil and gas contractors ",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Nurul Azharini",
      "location": "Lhokseumawe",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "PNS dan Jual Alat2 Home Decor",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Slamet Hadi",
      "location": "Yogyakarta",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "T. Mirzal Safari",
      "location": "BandaAceh",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Mahasiswa",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Zulfikar. S",
      "location": "Lhokseumawe",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "POLRI",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Farnia Ramadhani",
      "location": "JakartaSelatan",
      "school_sd": "SD PIM",
      "school_smp": "SMP PIM",
      "school_sma": "SMA YAPENA",
      "job": "Usaha Kedai Kopi KOMA KOPI MANGAT ",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Khairunnisa",
      "location": "BandarLampung",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA N 5 Palembang",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Dody Robinson Lubis",
      "location": "JakartaUtara",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMUN 4 Medan",
      "job": "Koordinator Media di Yayaysan Dokter Peduli ( doctorSHARE )",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "wiwien palupi",
      "location": "Yogyakarta",
      "school_sd": "SD 2",
      "school_smp": "SMP 1",
      "school_sma": "SMA Muhammadiyah 5 Yogyakarta",
      "job": "ibu rt, online shop",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Arie Willyana",
      "location": "KualaSimpang",
      "school_sd": "SD 1 dan SD 2",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "RSUD Kab. Aceh Tamiang",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "ratna ningsih",
      "location": "Meulaboh",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "jualan motor",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Rita",
      "location": "Banda Aceh",
      "school_sd": "SD 3",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "Jual buku/mainan edukasi & fashion/aksesoris muslim dewasa + anak2 ",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Andi irawan",
      "location": "Balikpapan",
      "school_sd": "SD 4",
      "school_smp": "SMP 1",
      "school_sma": "Smut krida nusantara bandung",
      "job": "Reservoir engineer, pertamina hulu mahakam, migas",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Aris Yulanda",
      "location": "Lhokseumawe",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "BRI",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Sebastian Widodo ",
      "location": "Jakarta",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "",
      "job": "Production House, Rental Equipment, Freelancer",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Dara Malahayati",
      "location": "Lhokseumawe",
      "school_sd": "SD 2",
      "school_smp": "SMP 1",
      "school_sma": "SMU Mosa BNA",
      "job": "Bisnis online",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Dithy yelina",
      "location": "Bandung",
      "school_sd": "SD 2",
      "school_smp": "SMP 1",
      "school_sma": "Bandung",
      "job": "Kafe ",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Safriani/cut zein",
      "location": "Medan",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "Medan",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Dian Hafrianni",
      "location": "TangerangSelatan",
      "school_sd": "SD 2",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "TARI MELLISA RAFAR",
      "location": "LHOKSEUMAWE",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "PNS",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Indri Irnandalia",
      "location": "TangerangSelatan",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMU Jakarta",
      "job": "Konveksi Mukena",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Sari Wardani",
      "location": "BandaAceh",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Dosen",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Teuku Anggara",
      "location": "Malang",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Maria Evayanty",
      "location": "Lhokseumawe",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Wiraswasta",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Fery Dermawan",
      "location": "Bogor",
      "school_sd": "SD 1",
      "school_smp": "Nurul Hakim Deli Serdang",
      "school_sma": "Al Karomah Brastagi",
      "job": "Wiraswasta",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Luthfi Al Rasyid",
      "location": "Medan",
      "school_sd": "SD 4",
      "school_smp": "SMP 1",
      "school_sma": "Medan",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Andalucia Alfan",
      "location": "Depok",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Ramayuda Rahmad",
      "location": "Yogyakarta",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "IAN PINOTO",
      "location": "BANDUNG",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "",
      "job": "Currently working in oil and gas industry.",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Debby wanty",
      "location": "Medan",
      "school_sd": "SD 2",
      "school_smp": "SMP 1",
      "school_sma": "Sma harapan medan",
      "job": "Klinik therapi anak berkebutuhan khusus",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Lidya visca nanda",
      "location": "JakartaSelatan",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "Qatar",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Hayria",
      "location": "Medan",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "Sudah di Medan",
      "job": "Ibu rumah tangga",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Muhammad Chandrataruna",
      "location": "TangerangSelatan",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMAN 4 Jakarta",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Nina Novera",
      "location": "TangerangSelatan",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "",
      "job": "Jasa - Event Organizer (Seminar, 3D Design, Conference)",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Vera verdyani",
      "location": "Jakarta",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Mardian aqsa",
      "location": "Balikpapan",
      "school_sd": "SD 2",
      "school_smp": "SMP 1",
      "school_sma": "Out",
      "job": "Assiaapp",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Syarifah marnita mutia",
      "location": "Batam",
      "school_sd": "SD 4",
      "school_smp": "SMP 2",
      "school_sma": "Bandung",
      "job": "Irt",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "JULIA BUDIANI",
      "location": "LHOKSEUMAWE",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMF Apipsu Medan",
      "job": "PNS",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Hady Muzakkir",
      "location": "Bireuen",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Retno estuning ratri",
      "location": "Bandung",
      "school_sd": "SD 3",
      "school_smp": "SMP 1",
      "school_sma": "Smat krida nusantara",
      "job": "Psikolog",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Erry Rustiansyah",
      "location": "Pontianak",
      "school_sd": "SD 4",
      "school_smp": "SMP 1",
      "school_sma": "SMA N 2 Medan",
      "job": "Perkebunan",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Intan Faridasari Kusumawaty",
      "location": "Depok",
      "school_sd": "SD 1",
      "school_smp": "SMP Harapan 2 Medan",
      "school_sma": "SMA 1 Medan",
      "job": "Dokter",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Siska mayasari",
      "location": "Bireuen ",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Baker bread and cake",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Fakhri Anindita",
      "location": "JakartaSelatan",
      "school_sd": "SD 1",
      "school_smp": "Di Bogor",
      "school_sma": "Di Bogor",
      "job": "Photographer",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Hendra Widiyanto",
      "location": "Tangerang Selatan",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMU Muhammadiyah 1",
      "job": "OHS Expert",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Reny amalia ",
      "location": "Pekanbaru ",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "Smun 9 malang",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Anna Millizia",
      "location": "Lhokseumawe",
      "school_sd": "SD 4",
      "school_smp": "SMP 2",
      "school_sma": "SMUN 1 Medan",
      "job": "Dokter spesialis anestesi",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Lina Susanti",
      "location": "Medan",
      "school_sd": "SD 3",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "Jual snack2, cemilan, kue kering",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Siska mayasari",
      "location": "Bireuen",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Baker bread cake",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Muhammad ichsan",
      "location": "Bireuen",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "Pegawai negri",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Aini Shafra Anwar (Aan) ",
      "location": "KomplekArun",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Konselor/therapis Anak Berkebutuhan Khusus\n",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": "Produksi makanan khas Abon dan Keumamah Tuna"
    },
    {
      "name": "Freya Amarantha Sutan Assin",
      "location": "Bali",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "Global Jaya",
      "job": "Fashion Design",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Safrina",
      "location": "Lhokseumawe",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "PNS",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Muhammad hamzah",
      "location": "Aceh",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Polri",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Maulana Kurniawan",
      "location": "Medan",
      "school_sd": "SD 2",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "Web/Mobile App Programmer",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Juliana",
      "location": "BandaAceh",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "ASN Kementerian Agama",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Cut Keumala Hayati",
      "location": "Sydney",
      "school_sd": "SD 4",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Mardianti",
      "location": "Langsa",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Dokter",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Frans Mario Halomoan Simanjuntak",
      "location": "TangerangSelatan",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMU Immanuel Medan",
      "job": "IT",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": "Bekerja di perusahaan IT yang fokus ke IT Network dan mempunyai usaha Mangat Delight yang menjual snack seperti brownies & cheese cake"
    },
    {
      "name": "Dian Hafrianni",
      "location": "TangerangSelatan",
      "school_sd": "SD 2",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "Ibu rumah tangga",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Harry Kurniawan",
      "location": "Binjai",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Photographer, Industrial Constractor, Macrame Artist.",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Nila Purnama",
      "location": "BandaAceh",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "ade irwansyah",
      "location": "medan",
      "school_sd": "SD 4",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "DJI BATTERY SOLUTION INDONESIA (DBSI Sumut),LIVE STREAMING & Event Organizer",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Fuady Azlin",
      "location": "Jakarta",
      "school_sd": "SD 4",
      "school_smp": "SMP 2",
      "school_sma": "SMANSA MEDAN",
      "job": "Konsultan dan TaakkaaT Coffee Owner",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Rezza Agusfian",
      "location": "Malang",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Meutia Handayani",
      "location": "Lhokseumawe",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Ibu rumah tangga",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "achmad yanie",
      "location": "pekanbaru ",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "event organizer (EO) , editor video",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "M.Ricci.L",
      "location": "Medan",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "Smu swasta harapan,medan",
      "job": "Wiraswasta",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Dian Agusta",
      "location": "Banten",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMU N 3 Banda Aceh",
      "job": "Chemical Industry",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Dinoe Romadesta",
      "location": "Medan",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMUN 4 Medan",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "WESTLY PANGGABEAN",
      "location": "BALI",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMUK IMMANUEL,  MEDAN",
      "job": "JASA",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Maulidya Rizki",
      "location": "Lhokseumawe",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "BSI Bank Syariah Indonesia ",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Sofran",
      "location": "BandaAceh",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Nella Nofita",
      "location": "Bekasi",
      "school_sd": "SD 4",
      "school_smp": "SMP 1",
      "school_sma": "",
      "job": "Behaviour analyst",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Zaid Arham",
      "location": "AcehBesar",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA Mosa",
      "job": "PNS",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Vicky F. Fakhrurrazi",
      "location": "Qatar",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMUN 46 Jakarta Selatan",
      "job": "Procurement, Contracting & Supply Chain Management",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Viviorini",
      "location": "Semarang",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "PNS",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "LENA ROMAWANA",
      "location": "BandaAceh",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA DI JOGJA",
      "job": "PT HM SAMPOERNA TBK",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "NOVALIANTO",
      "location": "AcehBesar",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMA YAPENA",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Fira rafina",
      "location": "Medan",
      "school_sd": "SD Al Alaq",
      "school_smp": "PonPes Alkautsar Alakbar medan",
      "school_sma": "SMA YAPENA",
      "job": "Ibu rumah tangga",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Ratna Mariska",
      "location": "Palembang",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "Bina Warga, Palembang",
      "job": "",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Fury Maulina",
      "location": "Amsterdam",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "Dosen",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Kurniawan Norat",
      "location": "Tangerang",
      "school_sd": "SD 3",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "BPOM",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Yvonne Lora Simamora (onni)",
      "location": "Bekasi",
      "school_sd": "SD 3",
      "school_smp": "SMP 1",
      "school_sma": "",
      "job": "Ibu rumah tangga",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "ABU ZABEDAN",
      "location": "YOGYAKARTA",
      "school_sd": "SD 1",
      "school_smp": "SMP 1",
      "school_sma": "SMU 2 DEPOK JAWA BARAT",
      "job": "Perbankan",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Juwita Apriyani",
      "location": "Medan",
      "school_sd": "SD 2",
      "school_smp": "Ponpes RH medan",
      "school_sma": "SMA YAPENA",
      "job": "IRT",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    },
    {
      "name": "Andalivia",
      "location": "TangerangSelatan",
      "school_sd": "SD 2",
      "school_smp": "SMP 2",
      "school_sma": "SMA YAPENA",
      "job": "IRT",
      "link_wa": "",
      "link_fb": "",
      "link_ig": "",
      "link_twitter": "",
      "link_linkedin": "",
      "img": "",
      "summary": ""
    }
]

export default friends